name: Test Suite

on:
  pull_request:
  push:
    branches: [ 1.x ]
  schedule: [ { cron: '0 8 * * *' } ]

jobs:
  static-analyze:
    name: "Static Analyze"
    uses: flow-php/actions/.github/workflows/composer-script-static-analyze.yaml@main
